---

- name: Install python-pexpect for dependency
  apt:
    name: python-pexpect
    state: present
    update_cache: yes
  tags:
    - install

- name: Install python-pymysql for dependency
  apt:
    name: python-pymysql
    state: present
    update_cache: yes
  tags:
    - install

- import_tasks: install_owncloud.yml
  tags:
    - install
    - install_owncloud

- import_tasks: configure_ssl.yml
  tags:
    - install
    - install_apache

- import_tasks: install_mariadb.yml
  tags:
    - install
    - install_mariadb
    
- import_tasks: install_php.yml
  tags:
    - install
    - install_php

- import_tasks: install_apache.yml
  tags:
    - install
    - install_apache

- import_tasks: uninstall.yml
  tags:
    - uninstall
